apiVersion: v1
kind: Service
metadata:
  name: keybuzz-studio-api
  namespace: keybuzz-studio-api-dev
  labels:
    app: keybuzz-studio-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4010
      protocol: TCP
      name: http
  selector:
    app: keybuzz-studio-api
