apiVersion: apps/v1
kind: Deployment
metadata:
  name: keybuzz-backend
  namespace: keybuzz-backend-prod
  labels:
    app: keybuzz-backend
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keybuzz-backend
  template:
    metadata:
      labels:
        app: keybuzz-backend
        env: production
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: keybuzz-backend
          image: ghcr.io/keybuzzio/keybuzz-backend:v1.0.41-ph263b-scheduler-prod
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: keybuzz-backend-db
            - secretRef:
                name: keybuzz-backend-secrets
            - secretRef:
                name: vault-token
                optional: true
            - secretRef:
                name: amazon-spapi-creds
            - secretRef:
                name: inbound-webhook-key
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4000"
            - name: KEYBUZZ_SUPERADMIN_EMAIL
              value: "admin@keybuzz.io"
            - name: VAULT_ADDR
              value: "http://vault.default.svc.cluster.local:8200"
            - name: ADMIN_CALLBACK_URL
              value: "https://client.keybuzz.io/inbound-email/amazon/callback"
            - name: KEYBUZZ_DEV_MODE
              value: "false"
            - name: DEV_AUTH
              value: "true"
            - name: KEYBUZZ_INTERNAL_PROXY_TOKEN
              value: "a0b9714c287bd18577f2e430770169e4b969bcfbbcedccdcf420cd09acd09147"
              valueFrom:
                secretKeyRef:
                  name: keybuzz-internal-proxy
                  key: token
            - name: AMAZON_SPAPI_REDIRECT_URI
              value: "https://backend.keybuzz.io/api/v1/marketplaces/amazon/oauth/callback"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-app-token
                  key: token
                  optional: true
            - name: NODE_EXTRA_CA_CERTS
              value: "/etc/ssl/vault/vault-ca.pem"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
