apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keybuzz-backend-secrets
  namespace: keybuzz-backend-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keybuzz-backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: keybuzz/prod/backend-jwt
        property: JWT_SECRET
    - secretKey: KEYBUZZ_INTERNAL_TOKEN
      remoteRef:
        key: keybuzz/internal-tokens
        property: KEYBUZZ_INTERNAL_TOKEN
    - secretKey: MINIO_ENDPOINT
      remoteRef:
        key: keybuzz/minio
        property: MINIO_ENDPOINT
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: keybuzz/minio
        property: MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: keybuzz/minio
        property: MINIO_SECRET_KEY
    - secretKey: MINIO_BUCKET_ATTACHMENTS
      remoteRef:
        key: keybuzz/minio
        property: MINIO_BUCKET_ATTACHMENTS
    - secretKey: PRODUCT_DATABASE_URL
      remoteRef:
        key: keybuzz/prod/backend-product-db
        property: PRODUCT_DATABASE_URL
