apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keybuzz-ses
  namespace: keybuzz-api-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keybuzz-ses
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secret/keybuzz/prod/ses
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/keybuzz/prod/ses
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: secret/keybuzz/prod/ses
        property: AWS_REGION
