apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: octopia-credentials
  namespace: keybuzz-api-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: octopia-credentials
    creationPolicy: Owner
  data:
    - secretKey: OCTOPIA_CLIENT_ID
      remoteRef:
        key: keybuzz/prod/octopia
        property: OCTOPIA_CLIENT_ID
    - secretKey: OCTOPIA_CLIENT_SECRET
      remoteRef:
        key: keybuzz/prod/octopia
        property: OCTOPIA_CLIENT_SECRET
    - secretKey: OCTOPIA_AUTH_URL
      remoteRef:
        key: keybuzz/prod/octopia
        property: OCTOPIA_AUTH_URL
    - secretKey: OCTOPIA_API_URL
      remoteRef:
        key: keybuzz/prod/octopia
        property: OCTOPIA_API_URL
