apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keybuzz-api-postgres
  namespace: keybuzz-api-prod
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keybuzz-api-postgres
    creationPolicy: Owner
  data:
    - secretKey: PGHOST
      remoteRef:
        key: secret/keybuzz/prod/db_api
        property: PGHOST
    - secretKey: PGPORT
      remoteRef:
        key: secret/keybuzz/prod/db_api
        property: PGPORT
    - secretKey: PGDATABASE
      remoteRef:
        key: secret/keybuzz/prod/db_api
        property: PGDATABASE
    - secretKey: PGUSER
      remoteRef:
        key: secret/keybuzz/prod/db_api
        property: PGUSER
    - secretKey: PGPASSWORD
      remoteRef:
        key: secret/keybuzz/prod/db_api
        property: PGPASSWORD
