apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keybuzz-api
  namespace: keybuzz-api-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - api.keybuzz.io
      secretName: keybuzz-api-prod-tls
  rules:
    - host: api.keybuzz.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keybuzz-api
                port:
                  number: 80
