apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keybuzz-auth-secrets
  namespace: keybuzz-client-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keybuzz-auth-secrets
    creationPolicy: Owner
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: secret/keybuzz/prod/auth
        property: NEXTAUTH_SECRET
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: secret/keybuzz/prod/auth
        property: GOOGLE_CLIENT_ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: secret/keybuzz/prod/auth
        property: GOOGLE_CLIENT_SECRET
    - secretKey: AZURE_AD_CLIENT_ID
      remoteRef:
        key: secret/keybuzz/prod/auth
        property: AZURE_AD_CLIENT_ID
    - secretKey: AZURE_AD_CLIENT_SECRET
      remoteRef:
        key: secret/keybuzz/prod/auth
        property: AZURE_AD_CLIENT_SECRET
    - secretKey: AZURE_AD_TENANT_ID
      remoteRef:
        key: secret/keybuzz/prod/auth
        property: AZURE_AD_TENANT_ID
