apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keybuzz-client
  namespace: keybuzz-client-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/limit-connections: '100'
    nginx.ingress.kubernetes.io/limit-rps: '50'
    nginx.ingress.kubernetes.io/limit-burst-multiplier: '5'
spec:
  tls:
  - hosts:
    - client.keybuzz.io
    secretName: keybuzz-client-prod-tls
  rules:
  - host: client.keybuzz.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keybuzz-client
            port:
              number: 80
