apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keybuzz-admin-v2-postgres
  namespace: keybuzz-admin-v2-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keybuzz-admin-v2-postgres
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: PGHOST
      remoteRef:
        key: keybuzz/admin-v2/postgres-prod
        property: PGHOST
    - secretKey: PGPORT
      remoteRef:
        key: keybuzz/admin-v2/postgres-prod
        property: PGPORT
    - secretKey: PGDATABASE
      remoteRef:
        key: keybuzz/admin-v2/postgres-prod
        property: PGDATABASE
    - secretKey: PGUSER
      remoteRef:
        key: keybuzz/admin-v2/postgres-prod
        property: PGUSER
    - secretKey: PGPASSWORD
      remoteRef:
        key: keybuzz/admin-v2/postgres-prod
        property: PGPASSWORD
