apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keybuzz-admin-v2
  name: keybuzz-admin-v2
  namespace: keybuzz-admin-v2-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keybuzz-admin-v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: keybuzz-admin-v2
    spec:
      containers:
      - name: keybuzz-admin-v2
        # ROLLBACK: v2.10.1-ph-admin-87-15b-dev
        image: ghcr.io/keybuzzio/keybuzz-admin:v2.11.0-tenant-foundation-dev
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: production
        - name: NEXT_PUBLIC_API_URL
          value: https://api-dev.keybuzz.io
        - name: NEXT_PUBLIC_APP_ENV
          value: development
        - name: NEXTAUTH_URL
          value: https://admin-dev.keybuzz.io
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              key: NEXTAUTH_SECRET
              name: keybuzz-admin-v2-auth
              optional: true
        - name: KEYBUZZ_API_INTERNAL_URL
          value: http://keybuzz-api.keybuzz-api-dev.svc.cluster.local:3001
        - name: ADMIN_BOOTSTRAP_EMAIL
          valueFrom:
            secretKeyRef:
              key: ADMIN_BOOTSTRAP_EMAIL
              name: keybuzz-admin-v2-bootstrap
        - name: ADMIN_BOOTSTRAP_PASSWORD_HASH
          valueFrom:
            secretKeyRef:
              key: ADMIN_BOOTSTRAP_PASSWORD_HASH
              name: keybuzz-admin-v2-bootstrap
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              key: PGHOST
              name: keybuzz-admin-v2-postgres
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              key: PGPORT
              name: keybuzz-admin-v2-postgres
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              key: PGDATABASE
              name: keybuzz-admin-v2-postgres
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: PGUSER
              name: keybuzz-admin-v2-postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: PGPASSWORD
              name: keybuzz-admin-v2-postgres
        ports:
        - containerPort: 3000
          name: http
        livenessProbe:
          httpGet:
            path: /login
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      imagePullSecrets:
      - name: ghcr-secret
