#!/bin/bash
# Deploy SSH key from install-v3 to all rebuildable servers (47 servers)
# PH2-04: SSH Mesh Key Deployment
# This script deploys /root/.ssh/id_rsa_keybuzz_v3.pub to all servers via their public IPs
# Uses sshpass with Hetzner root password from environment variable

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "${SCRIPT_DIR}")"
TSV_FILE="${INFRA_DIR}/servers/servers_v3.tsv"
SSH_KEY="/root/.ssh/id_rsa_keybuzz_v3.pub"
SSH_KEY_PRIV="/root/.ssh/id_rsa_keybuzz_v3"
LOG_DIR="/opt/keybuzz/logs/phase2"
LOG_FILE="${LOG_DIR}/ssh-key-deployment.log"
ENV_FILE="/opt/keybuzz/credentials/hcloud.env"
EXCLUDED_HOSTS=("install-01" "install-v3")

# Ensure log directory exists
mkdir -p "${LOG_DIR}"

# Initialize log
cat > "${LOG_FILE}" << EOF
========================================
SSH Key Mesh Deployment Log
========================================
Started: $(date -Iseconds)
Key: ${SSH_KEY}
Target: All rebuildable servers (excluding bastions)
========================================

EOF

# Function to log
log_info() {
    echo "[INFO] $1" | tee -a "${LOG_FILE}"
}

log_success() {
    echo "[SUCCESS] $1" | tee -a "${LOG_FILE}"
}

log_error() {
    echo "[ERROR] $1" | tee -a "${LOG_FILE}"
}

# Check SSH key exists
if [[ ! -f "${SSH_KEY}" ]]; then
    log_error "SSH public key not found: ${SSH_KEY}"
    exit 1
fi

if [[ ! -f "${SSH_KEY_PRIV}" ]]; then
    log_error "SSH private key not found: ${SSH_KEY_PRIV}"
    exit 1
fi

log_info "SSH key found: ${SSH_KEY}"

# Install sshpass if not available
if ! command -v sshpass &> /dev/null; then
    log_info "Installing sshpass for automated SSH key deployment..."
    apt-get update -qq && apt-get install -y sshpass > /dev/null 2>&1
fi

log_info "sshpass installed: $(command -v sshpass)"

# Load Hetzner token
if [[ -f "${ENV_FILE}" ]]; then
    source "${ENV_FILE}"
    export HCLOUD_TOKEN
fi

if [[ -z "${HCLOUD_TOKEN:-}" ]]; then
    log_error "HCLOUD_TOKEN not found. Please configure it in ${ENV_FILE}"
    exit 1
fi

log_info "Reading server list from: ${TSV_FILE}"

# Parse TSV and extract rebuildable servers using awk
TEMP_CSV="/tmp/rebuildable_servers.csv"

# Extract column indices from header
HEADER=$(head -1 "${TSV_FILE}")
HOSTNAME_COL=$(echo "${HEADER}" | awk -F'\t' '{for(i=1;i<=NF;i++) if($i=="HOSTNAME") print i}')
IP_PUB_COL=$(echo "${HEADER}" | awk -F'\t' '{for(i=1;i<=NF;i++) if($i=="IP_PUBLIQUE") print i}')
IP_PRIV_COL=$(echo "${HEADER}" | awk -F'\t' '{for(i=1;i<=NF;i++) if($i=="IP_PRIVEE") print i}')
ROLE_COL=$(echo "${HEADER}" | awk -F'\t' '{for(i=1;i<=NF;i++) if($i=="ROLE_V3") print i}')

log_info "TSV columns: HOSTNAME=${HOSTNAME_COL}, IP_PUBLIQUE=${IP_PUB_COL}, IP_PRIVEE=${IP_PRIV_COL}, ROLE_V3=${ROLE_COL}"

# Generate CSV file with rebuildable servers
echo "hostname,ip_public,ip_private,role" > "${TEMP_CSV}"

# Process TSV file (skip header, exclude install-01 and install-v3)
tail -n +2 "${TSV_FILE}" | while IFS=$'\t' read -r line; do
    hostname=$(echo "${line}" | awk -F'\t' -v col="${HOSTNAME_COL}" '{print $col}' | xargs)
    
    # Skip if hostname is empty or in excluded list
    [[ -z "${hostname}" ]] && continue
    [[ "${hostname}" == "install-01" ]] && continue
    [[ "${hostname}" == "install-v3" ]] && continue
    
    ip_public=$(echo "${line}" | awk -F'\t' -v col="${IP_PUB_COL}" '{print $col}' | xargs)
    ip_private=$(echo "${line}" | awk -F'\t' -v col="${IP_PRIV_COL}" '{print $col}' | xargs)
    role=$(echo "${line}" | awk -F'\t' -v col="${ROLE_COL}" '{print $col}' | xargs)
    
    # Only add if IP public is present
    if [[ -n "${ip_public}" ]]; then
        echo "${hostname},${ip_public},${ip_private},${role}" >> "${TEMP_CSV}"
    fi
done

if [[ ! -f "${TEMP_CSV}" ]]; then
    log_error "Failed to generate server list"
    exit 1
fi

TOTAL_SERVERS=$(tail -n +2 "${TEMP_CSV}" | wc -l)
log_info "Total servers to process: ${TOTAL_SERVERS}"

# Check for Hetzner root password
# This password is the same for all servers rebuilt in PHASE 1
# It was generated by Hetzner during the rebuild operation
if [[ -z "${HETZNER_ROOT_PASSWORD:-}" ]]; then
    log_error "HETZNER_ROOT_PASSWORD not set. Please export it before running this script."
    log_error "Example: export HETZNER_ROOT_PASSWORD='your-hetzner-root-password'"
    log_error "This password can be found in Hetzner Cloud console or email after server rebuild."
    log_error "Note: All servers rebuilt in PHASE 1 should have the same root password."
    rm -f "${TEMP_CSV}"
    exit 1
fi

log_info "Using Hetzner root password (length: ${#HETZNER_ROOT_PASSWORD} chars)"

# Counters
SUCCESS_COUNT=0
FAILED_COUNT=0
FAILED_SERVERS=()

# Deploy key to each server
log_info "Starting SSH key deployment..."
echo ""

while IFS=',' read -r hostname ip_public ip_private role; do
    # Skip header
    [[ "${hostname}" == "hostname" ]] && continue
    
    log_info "Processing: ${hostname} (${ip_public}) - ${role}"
    
    # Use Hetzner root password from environment variable
    ROOT_PASSWORD="${HETZNER_ROOT_PASSWORD}"
    
    # Deploy SSH key using ssh-copy-id with sshpass
    log_info "  Deploying SSH key..."
    if sshpass -p "${ROOT_PASSWORD}" ssh-copy-id \
        -i "${SSH_KEY}" \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/root/.ssh/known_hosts \
        -o ConnectTimeout=15 \
        -o PasswordAuthentication=yes \
        root@"${ip_public}" \
        >> "${LOG_FILE}" 2>&1; then
        log_success "${hostname} (${ip_public}): Key deployed successfully"
        
        # Test SSH connection without password
        if ssh -i "${SSH_KEY_PRIV}" \
            -o StrictHostKeyChecking=no \
            -o ConnectTimeout=5 \
            -o PasswordAuthentication=no \
            root@"${ip_public}" "echo 'SSH_KEY_TEST_OK'" >> "${LOG_FILE}" 2>&1; then
            log_success "${hostname} (${ip_public}): SSH key authentication verified"
        else
            log_error "${hostname} (${ip_public}): SSH key deployed but authentication test failed"
        fi
        
        SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
    else
        EXIT_CODE=$?
        log_error "${hostname} (${ip_public}): Deployment failed (exit code: ${EXIT_CODE})"
        FAILED_COUNT=$((FAILED_COUNT + 1))
        FAILED_SERVERS+=("${hostname} (${ip_public})")
    fi
    
    # Clear password from memory (best effort)
    ROOT_PASSWORD=""
    
    echo ""
    
done < "${TEMP_CSV}"

# Cleanup
rm -f "${TEMP_CSV}"

# Final summary
echo "" | tee -a "${LOG_FILE}"
echo "========================================" | tee -a "${LOG_FILE}"
echo "SSH Key Deployment Summary" | tee -a "${LOG_FILE}"
echo "========================================" | tee -a "${LOG_FILE}"
echo "Total servers: ${TOTAL_SERVERS}" | tee -a "${LOG_FILE}"
echo "Success: ${SUCCESS_COUNT}" | tee -a "${LOG_FILE}"
echo "Failed: ${FAILED_COUNT}" | tee -a "${LOG_FILE}"
echo "Completed: $(date -Iseconds)" | tee -a "${LOG_FILE}"
echo "" | tee -a "${LOG_FILE}"

if [[ ${FAILED_COUNT} -gt 0 ]]; then
    echo "Failed servers:" | tee -a "${LOG_FILE}"
    for server in "${FAILED_SERVERS[@]}"; do
        echo "  - ${server}" | tee -a "${LOG_FILE}"
    done
    echo "" | tee -a "${LOG_FILE}"
fi

echo "========================================" | tee -a "${LOG_FILE}"

# Exit with error if any failed
if [[ ${FAILED_COUNT} -gt 0 ]]; then
    log_error "Deployment completed with ${FAILED_COUNT} failure(s)"
    exit 1
else
    log_success "All ${TOTAL_SERVERS} servers processed successfully"
    exit 0
fi

